"""empty message

Revision ID: 9c11ced12d92
Revises: c52ed682f5bc
Create Date: 2022-11-08 19:06:35.494519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c11ced12d92'
down_revision = 'c52ed682f5bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
