"""empty message

Revision ID: c52ed682f5bc
Revises: 7de05bcba294
Create Date: 2022-11-08 19:00:36.176964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52ed682f5bc'
down_revision = '7de05bcba294'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
